<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MT-YJTANG-DESKT" failures="1" tests="3" name="com.upgrade.challenge.testing.API.testEndPoints.states" time="0.506" errors="0" timestamp="25 Jul 2019 23:23:17 GMT" skipped="0">
  <testcase classname="com.upgrade.challenge.testing.API.testEndPoints.states" name="test2_onlyOneStateAge19" time="0.097"/>
  <testcase classname="com.upgrade.challenge.testing.API.testEndPoints.states" name="test3_GeorgiaIsOnlyStateHasAmount3005" time="0.046"/>
  <testcase classname="com.upgrade.challenge.testing.API.testEndPoints.states" name="test1_statesTotalSize48" time="0.363">
    <failure message="
Expecting:
 &lt;1&gt;
to be equal to:
 &lt;0&gt;
but was not." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
Expecting:
 <1>
to be equal to:
 <0>
but was not.
at com.upgrade.challenge.testing.API.testEndPoints.states.test1_statesTotalSize48(states.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- test1_statesTotalSize48 -->
</testsuite> <!-- com.upgrade.challenge.testing.API.testEndPoints.states -->
